defw:
    parent-address: ${DEFW_PARENT_ADDR}
    parent-port: ${DEFW_PARENT_PORT}
    parent-hostname: ${DEFW_PARENT_HOSTNAME}
    parent-name: ${DEFW_PARENT_NAME}
    name: ${DEFW_AGENT_NAME}
    listen-port: ${DEFW_LISTEN_PORT}
    telnet-port: ${DEFW_TELNET_PORT}
    shell: ${DEFW_SHELL_TYPE}
    type: ${DEFW_AGENT_TYPE}
    path: ${DEFW_PATH}
    tmp: ${DEFW_LOG_DIR}
    loglevel: ${DEFW_LOG_LEVEL}
    external-services: ${DEFW_EXTERNAL_SERVICES_PATH}
    external-service-apis: ${DEFW_EXTERNAL_SERVICE_APIS_PATH}
    external-experiments: ${DEFW_EXTERNAL_EXPERIMENTS_PATH}
    expected-agent-count: ${DEFW_EXPECTED_AGENT_COUNT}
